--- #YAML:1.0
name:                QualysGuard-Request
version:             0.01
abstract:            Simple interface to QualysGuard API
license:             ~
author:              
    - Patrick Devlin <pdevlin@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          1.04
    HTTP::Request:                 1.4
    IO::File:                      1.13
    LWP::UserAgent:                2.036
    Net::SSL:                      2.84
    Scalar::Util:                  1.19
    Test::More:                    0.78
    URI::Escape:                   3.28
    XML::XPath:                    1.13
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
